version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: python --version
      - run: &myrun echo "Running tests on Python 3.9"
  test_3_10:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: python --version
      - run: *myrun
  test_3_12:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: python --version
      - run: *myrun

workflows:
  version: 2
  test_multiple_python_versions:
    jobs:
      - test
      - test_3_10
      - test_3_12