version: 2.1

jobs:
  test_3.12:
    docker:
      - image: cimg/python:3.12.12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -e .[tests]
      - run:
          name: Run pytests with coverage
          command: | 
            mkdir test-results
            pytest --cov=your_package --cov-fail-under=80 --junitxml=test-results/junit.xml
  test_3.9:
    docker:
      - image: cimg/python:3.9.18
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -e .[tests]
      - run:
          name: Run pytests with coverage
          command: | 
            mkdir test-results
            pytest --cov=your_package --cov-fail-under=80 --junitxml=test-results/junit.xml
  test_3.11:
    docker:
      - image: cimg/python:3.11.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -e .[tests]
      - run:
          name: Run pytests with coverage
          command: | 
            mkdir test-results
            pytest --cov=your_package --cov-fail-under=80 --junitxml=test-results/junit.xml
workflows:
  test-workflow:
    jobs:
      - test_3.9
      - test_3.11
      - test_3.12